theme: jekyll-theme-cayman
title: Tutorato Informatica UniTN
description: Pagina non ufficiale del tutorato per il corso di Informatica della Laurea in Matematica a Trento
github:
  is_project_page: false
